### ISSUE TITLE
Not found ecoNavi mode

### ISSUE THREAD

**Issue by lucaswong** [sockless-coding/panasonic_cc#188]
Is it possible to add one more function, the ecoNavi mode? When I turned on my A/C, I couldn't find any way to turn the ecoNavi mode on. Thank you.

**Comment by lucaswong** [comment]
![WhatsApp Image 2024-05-24 at 11 09 04](https://github.com/sockless-coding/panasonic_cc/assets/488576/5b998477-1cea-4241-812f-4e1155272247)

**Comment by lucaswong** [comment]
When i am reading python code. I found that in pcomfortcloud -> session.py including ecoNavi code

`'ecoNavi': 'ecoNavi' in data and data['ecoNavi'],`

but not _main_.py

` '-e', '--eco',
        choices=[
            pcomfortcloud.constants.EcoMode.Auto.name,
            pcomfortcloud.constants.EcoMode.Quiet.name,
            pcomfortcloud.constants.EcoMode.Powerful.name],
        help='Eco mode')`

**Comment by thewan056** [comment]
I would like to see this feature added as well, as this allows users to save power.

**Comment by MatthK** [comment]
I'd opt in for that "Powerful" option to be added. While it does not exist in the Panasonic Comfort Cloud app itself, my A/C has that option on the infrared remote. It basically turns on full fan mode for a few minutes and then goes back to the same mode as before.
Before they changed to the new authorization, I had my own integration on a personal home page and used that function regularly. So this would be a really big plus.

**Comment by sockless-coding** [comment]
My device doesn't have it, but it looks like it's just a simple on/off switch...
Shouldn't be that hard to add

**Comment by sockless-coding** [comment]
Should be added in v1.0.50 (cant verify my self)

**Comment by sockless-coding** [comment]
Yeah noticed I didn't add it to the async version of setup entry, it will show up as a separate switch

**Comment by sockless-coding** [comment]
@thewan056 could you try v1.0.51

**Comment by thewan056** [comment]
I just tried 1.0.51. The Eco Navi switch has appeared for me. But it does not work. Turning it on does nothing, it reverts back to off. Turning on eco navi in my panasonic cc app on my phone doesnt change the switch to on.

I tried removing and readding the integration just in case, it still doesn't work.

**Comment by sockless-coding** [comment]
Found some copy and paste bugs, they should be fixed in v1.0.52

**Comment by thewan056** [comment]
Same as before for v1.0.52. Not working.

**Comment by thewan056** [comment]
`2024-06-29 18:52:46.687 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Set Yellow Room Cooler eco navi mode On
2024-06-29 18:52:47.293 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] POST url: https://accsmart.panasonic.com/deviceStatus/control, data: {'deviceGuid': 'C576719693', 'parameters': {}}, response: {"result":0}
2024-06-29 18:52:47.951 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/C576719693, response: {"timestamp":1719658367857,"permission":3,"summerHouse":0,"iAutoX":true,"nanoe":true,"nanoeStandAlone":true,"autoMode":false,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":true,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":false,"ecoFunction":0,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"parameters":{"ecoFunctionData":0,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":28.5,"fanSpeed":5,"fanAutoMode":0,"airSwingUD":0,"airSwingLR":2,"airDirection":0,"ecoMode":0,"ecoNavi":1,"nanoe":2,"iAuto":1,"insideTemperature":25,"outTemperature":31,"airQuality":0},"deviceNanoe":1,"visualizationAvlFlg":true,"simulationShowFlg":false,"simulationSettingFlg":true,"simulationSettings":{"no":4,"shapeId":0,"positionId":1,"widthId":1,"levelGroup":[120,300,840],"devPositionTypeId":0,"nanoeOnTime":5892}}
2024-06-29 18:52:47.951 DEBUG (MainThread) [custom_components.panasonic_cc.panasonic] Data: <custom_components.panasonic_cc.pcomfortcloud.panasonicdevice.PanasonicDevice object at 0x7fa256cf8410>`

checking the debug log, when i try to toggle the eco navi switch, the sent parameters is blank.

**Comment by sockless-coding** [comment]
Try v1.0.54 the parameters didn't get forwarded all the way

**Comment by MatthK** [comment]
I just updated to v1.0.54 and hoped that would work now. However, it seems I can't select the eco navi mode from HA. I now also "lost" one of my 4 A/Cs. I can still see a few Entities of it, but not the climate one. So I can't turn it on/off or change the temperature.

The switch Entitiy for all 4 A/Cs has a red ! status, same with the sensor.outside_temperature.

And I also noticed, that the Powerful mode disappeared. And if possible, I'd also can't find the Quiet mode in HA.

**Comment by thewan056** [comment]
I think v1.0.54 broke something. My AC became unavailable. Checking the log while reloading the integration i get:

2024-06-29 20:27:00.084 WARNING (MainThread) [custom_components.panasonic_cc.panasonic] Failed to renew token for device xxxx (not sure if this supposed to be a secret or not), giving up for now

Reverting to v1.0.53 didn't fix it. I can't test it for now.

**Comment by sockless-coding** [comment]
@thewan056 then there is a parsing issue the error message is wrong (its from the old authentication)...
Could you provide the debug log I need a status request response they look like this:
`[custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/<device id>, response: ...`

**Comment by lucaswong** [comment]
@thewan056 May I know your air conditioner model? My model is CS-RU12YKA.
@sockless-coding I want to express a heartfelt thank you for supporting us first. In my situation, even after updating to version 1.0.51 or 1.0.54, the Econavi switch still does not appear for me.

**Comment by sockless-coding** [comment]
I've release v1.0.55 it should hopefully work better and not fail completely if there are any parsing errors

**Comment by thewan056** [comment]
I updated to v1.0.56 before checking back here and everything is working now. Econavi is also working fine.

**Comment by lucaswong** [comment]
2024-06-30 22:38:07.425 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-RU12YKA%2BE110201042, response: {"timestamp":1719758287350,"permission":3,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":1,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":2,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":24,"fanSpeed":0,"fanAutoMode":3,"airSwingLR":2,"airSwingUD":0,"ecoMode":0,"ecoNavi":0,"nanoe":2,"iAuto":0,"airDirection":1,"insideTemperature":23,"outTemperature":28,"airQuality":0},"deviceNanoe":1,"visualizationAvlFlg":true,"simulationShowFlg":true,"simulationSettingFlg":true,"simulationSettings":{"no":14,"shapeId":1,"positionId":2,"widthId":3,"levelGroup":[120,300,840],"devPositionTypeId":0,"nanoeOnTime":8625}}


The debug logs showing "ecoNavi":false, but i have enabled the ecoNavi mode in the panasonic mobile app like my screen shot before. Are there any idea in this situation ? Thank you.

**Comment by lucaswong** [comment]
The debug logs showing "ecoNavi":false, but i have enabled the ecoNavi mode in the panasonic mobile app like my screen shot before. Are there any idea in this situation ? Thank you

**Comment by thewan056** [comment]
> 2024-06-30 22:38:07.425 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] GET url: https://accsmart.panasonic.com/deviceStatus/CS-RU12YKA%2BE110201042, response: {"timestamp":1719758287350,"permission":3,"summerHouse":0,"iAutoX":false,"nanoe":true,"nanoeStandAlone":true,"autoMode":true,"heatMode":false,"fanMode":false,"dryMode":true,"coolMode":true,"ecoNavi":false,"powerfulMode":true,"quietMode":true,"airSwingLR":true,"autoSwingUD":true,"ecoFunction":1,"temperatureUnit":0,"modeAvlList":{"autoMode":1},"nanoeList":{"visualizationShow":0},"clothesDrying":false,"insideCleaning":false,"fireplace":false,"pairedFlg":false,"parameters":{"ecoFunctionData":2,"insideCleaning":0,"fireplace":0,"lastSettingMode":0,"operate":1,"operationMode":2,"temperatureSet":24,"fanSpeed":0,"fanAutoMode":3,"airSwingLR":2,"airSwingUD":0,"ecoMode":0,"ecoNavi":0,"nanoe":2,"iAuto":0,"airDirection":1,"insideTemperature":23,"outTemperature":28,"airQuality":0},"deviceNanoe":1,"visualizationAvlFlg":true,"simulationShowFlg":true,"simulationSettingFlg":true,"simulationSettings":{"no":14,"shapeId":1,"positionId":2,"widthId":3,"levelGroup":[120,300,840],"devPositionTypeId":0,"nanoeOnTime":8625}}
> 
> The debug logs showing "ecoNavi":false, but i have enabled the ecoNavi mode in the panasonic mobile app like my screen shot before. Are there any idea in this situation ? Thank you.

@lucaswong cc app:

> ![WhatsApp Image 2024-05-24 at 11 09 04](https://private-user-images.githubusercontent.com/488576/333429173-5b998477-1cea-4241-812f-4e1155272247.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NjkwODMsIm5iZiI6MTcxOTc2ODc4MywicGF0aCI6Ii80ODg1NzYvMzMzNDI5MTczLTViOTk4NDc3LTFjZWEtNDI0MS04MTJmLTRlMTE1NTI3MjI0Ny5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MzBUMTczMzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmNlOTgzMTcyMTg3YTU2MjlhYWQyMmE5MmM0NzZjOGFjNzFmN2EzOWFmNWI2MjMxNTU0NmJhM2M1NDZmNWFkMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0mQ9syBQceFChUMxnXg4CRPMYwJDcuB-fsA7foZn5qs)

Mine:

![Screenshot_20240701-013157](https://github.com/sockless-coding/panasonic_cc/assets/24851051/39f7f8eb-92dc-4046-9439-5f64c1ecf801)

And my log says ecoNavi: true. Maybe possible that for your model the function is just named Eco based on your picture, instead of Econavi, like in my picture? So when this integration checks whether your model supports Econavi, it returns false because it is a different name.

**Comment by sockless-coding** [comment]
@lucaswong I'm guessing your eco function is linked to the `ecoFunction` and not `ecoNavi`
Since you have `"ecoFunction":1` under the feature section and `"ecoFunctionData":2` under the parameters

**Comment by sockless-coding** [comment]
Brilliant, the eco function on that model is called AI ECO...

**Comment by sockless-coding** [comment]
@lucaswong AI Eco is available in v1.0.57

**Comment by lucaswong** [comment]
> @lucaswong I'm guessing your eco function is linked to the `ecoFunction` and not `ecoNavi` Since you have `"ecoFunction":1` under the feature section and `"ecoFunctionData":2` under the parameters

@sockless-coding Yes, I found that if I turn off the "AI ECO" in the mobile app,  `"ecoFunctionData":2` changes to `"ecoFunctionData":1`.

I have updated to version 1.0.57, but the new "AI ECO" switch button doesn't appear for me, and it seems to have affected the PanasonicNanoeSwitch function.

Log message:

`2024-07-02 08:59:24.435 DEBUG (MainThread) [custom_components.panasonic_cc.pcomfortcloud.panasonicsession] Access token is valid`

`2024-07-02 08:59:32.123 ERROR (MainThread) [homeassistant.components.switch] Error while setting up panasonic_cc platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/panasonic_cc/switch.py", line 34, in async_setup_entry
    devices.append(PanasonicNanoeSwitch(device))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/panasonic_cc/switch.py", line 50, in __init__
    self._attr_entity_registry_enabled_default
AttributeError: 'PanasonicNanoeSwitch' object has no attribute '__attr_entity_registry_enabled_default'. Did you mean: '_attr_entity_registry_enabled_default'?`

**Comment by sockless-coding** [comment]
Some unfinished code was included, I've removed it and released v1.0.58

**Comment by lucaswong** [comment]
![2024-07-02 16_26_01-Lucas](https://github.com/sockless-coding/panasonic_cc/assets/488576/237651b6-3537-4d22-aaa7-9bca409cdc58)
NanoeX and AI ECO switch buttons are working normally now. Thank you.
