### ISSUE TITLE
Unavailable and cannot reinstall

### ISSUE THREAD

**Issue by andrew312mills** [sockless-coding/panasonic_cc#23]
today the heat pump became unavailable, and even though it is accessible in the comfort cloud android app, it has not come back up in HA.
I removed all and reinstalled in HACS as I had done the first time, and when I enter my user name and password I get the message
"Aborted
Unexpected error creating device."

I even created a new HA and tried to install ,but have the same issue of unexpected error.

it seems broken, and this was the main reason for getting HA

**Comment by hemaris-8b** [comment]
Seems that Panasonic has updated  Comfort Cloud making the present setup to fail. My log has stated to show errors last night:



Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/panasonic_cc/panasonic.py:23
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:51:41 AM (4 occurrences)
Last logged: 7:51:53 AM
[140199811433760] Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}

Traceback (most recent call last):
  File "/config/custom_components/panasonic_cc/panasonic.py", line 21, in wrapper_call
    func(*args, **kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 321, in set_device
    self._api.set_device(
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 389, in set_device
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"Token expires","code":4100}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1445, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1480, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 593, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 630, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/panasonic_cc/climate.py", line 106, in async_set_temperature
    await self._api.set_temperature(**kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 241, in set_temperature
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/panasonic_cc/panasonic.py", line 23, in wrapper_call
    args[0]._api.login()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 99, in login
    self._create_token()
  File "/usr/local/lib/python3.8/site-packages/pcomfortcloud/session.py", line 132, in _create_token
    raise ResponseError(response.status_code, response.text)
pcomfortcloud.session.ResponseError: Invalid response, status code: 401 - Data: {"message":"New version app has been published","code":4106}

**Comment by andrew312mills** [comment]
After all my playing, thats what I thought, especially since the android app went down also.

I assume you will be working on it.
I'll buy you "another coffee".

Andrew

sent from my mobile

Almost Dead Yesterday
Possibly Dead Tomorrow
GLORIOUSLY ALIVE TODAY
________________________________

**Comment by hemaris-8b** [comment]
> 
> After all my playing, thats what I thought, especially since the android app went down also. 

I  have problems only with HA, but my android app work normally. So this seems to be specific to HA.

**Comment by sockless-coding** [comment]
I've released a new version (v1.0.23) that should fix this issue, Panasonic made some changes to their API.

**Comment by hemaris-8b** [comment]
I installed the new versions and it woks perfectly. Many thanks for superfast response!

**Comment by andrew312mills** [comment]
thanks heaps, coffee bought, enjoy.

**Comment by svlkent** [comment]
Hello! Just updated. Still not possible to use.
Install in HACS, added in cofiguration, enter name and password
"Aborted! Unexpected error creating device."
Hav uninstalled everything and installed again. Same error

**Comment by hemaris-8b** [comment]
> 
> 
> Hello! Just updated. Still not possible to use.
> Install in HACS, added in cofiguration, enter name and password
> "Aborted! Unexpected error creating device."
> Hav uninstalled everything and installed again. Same error

Have you tried to install through GUI:
Configuration>Integrations>" +add Integration" button at the bottom of the screen

This worked for me.

**Comment by svlkent** [comment]
> > Hello! Just updated. Still not possible to use.
> > Install in HACS, added in cofiguration, enter name and password
> > "Aborted! Unexpected error creating device."
> > Hav uninstalled everything and installed again. Same error
> 
> Have you tried to install through GUI:
> Configuration>Integrations>" +add Integration" button at the bottom of the screen
> 
> This worked for me.

Yes, that's where I get the error message

**Comment by svlkent** [comment]
In the log I get
Unexpected error creating device
14:29:04 – Panasonic Comfort Cloud (ERROR) 

Should I uninstall in HACS and reinstall again?

**Comment by hemaris-8b** [comment]
I did the initial install Configuration>Integrations>" +add Integration"
For update today I did: HACS>integrations>Panasonic_cc card>...>update information (think it was that)>>>reboot

**Comment by svlkent** [comment]
> I did the initial install Configuration>Integrations>" +add Integration"
> For update today I did: HACS>integrations>Panasonic_cc card>...>update information (think it was that)>>>reboot

Hmmm - When I saw the error I uninstalled from "Configuration - Integrations" first
Then I saw the update in HACS nd updated
Then, as it didnt work, I uninstalled everything and started over
Still no luck
I try to do it all one more time

**Comment by svlkent** [comment]
Do you guys install both "Panasonic Comfort Cloud HA Component" and "Panasonic Comfort Cloud" in HACS?

**Comment by hemaris-8b** [comment]
Hmm I think I only installed Panasonic Comfort Cloud. Cant see "Panasonic Comfort Cloud HA Component"  in HACS at all.

**Comment by massive** [comment]
Thanks for fixing this @sockless-coding! I bought you some coffee.

**Comment by svlkent** [comment]
> I've released a new version (v1.0.23) that should fix this issue, Panasonic made some changes to their API.

Hello again! Uninstalled from HACS, reboot , reinstalled, reboot, same issue  when trying to add the component in "Configuration - Integrations"
* Add component "Panasonic Comfort Cloud"
* Enter user name and password - Enter
* "Unexpected error creating device"

:(

**Comment by svlkent** [comment]
SOLVED! After updating HA and HA OS to latest version the integration works

**Comment by sockless-coding** [comment]
Thanks for all the coffee!

@svlkent glad to hear that you got it working.
FYI "Panasonic Comfort Cloud HA component" is a different component, and it's not needed nor a part of this component.
