### ISSUE TITLE
Login not possible anymore. Missing required parameter: code

### ISSUE THREAD

**Issue by geby85** [sockless-coding/panasonic_cc#320]
### Checklist

- [X] I have verified that the account and device works in the Comfort Cloud App.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/sockless-coding/panasonic_cc/issues?q=is%3Aissue+label%3A"bug"+)..

### What version of Home Assistant Core?

core-2024.9.3

### Describe the issue

I can not login to the cloud from the plugin anymore.

I noticed, that Panasonic now sends me mails, if I logg into my account in the iOS App or Web, which I never got before.
I also notice, that I now seem to have mea activated via sms code. 

I tried to deactivate ist under https://accountglb.digital.panasonic.com but that seems not to be possible.

### Error/Debug Logs

```text
Logger: custom_components.panasonic_cc.config_flow
Quelle: custom_components/panasonic_cc/config_flow.py:142
Integration: Panasonic Comfort Cloud (Dokumentation, Probleme)
Erstmals aufgetreten: 14:12:40 (1 Vorkommnisse)
Zuletzt protokolliert: 14:12:40

Bad logger message: Unexpected error creating device ((ResponseError('(get_token: Expected status code 200, received: 400: {"error":"invalid_request","error_description":"Missing required parameter: code"}'),))
```

**Comment by geby85** [comment]
It seems to be related to my installation. I added the plugin in another installation and could connect my account from there. Strange.

**Comment by geby85** [comment]
Problem is solved now, but I have no idea how. It suddenly is working again :/

**Comment by DanielSobczak** [comment]
Hey, I'm having the same issue right now. 
It was working fine for months but after HA update it stopped, I tried to log out and then log in on mobile Cloud app, reset 2FA and in the end reinstall whole integration - still getting the issue with the `code` missing.
Looking at the logs it seems that the `Locations` header doesn't contain the `code` attribute anymore while request are made from this integration.
Any idea what I can try next?
